- name: Change host variable
  hosts: localhost
  connection: local
  tasks:
    - name: Use hostname from env var working_host
      add_host:
        name: "{{ working_host }}"
        groups: working_group
  tags:
    - vars

- name: Create VM Template
  hosts: working_group
  gather_facts: true
  remote_user: root
  # become: true
  vars:
    # ansible_python_interpreter: /usr/bin/python
    ansible_ssh_port: 22
    ANSIBLE_ROLES_PATH: roles/
    template_name: debian-10-tpl
    vm_memory: 4096
    vm_cores: 4
    vm_sockets: 1
    numa: 1
    # vars to check before create VM
    storage: "local-zfs" # pvesm status
    VM_ID: 7012
    network_bridge: "vmbr0"
  roles:
    - deploy_debian10_on_proxmox
